name: build

on: [push, pull_request]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [2.7, 3.6, 3.7, 3.8, 3.9]
        perl-version: [latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Perl ${{ matrix.perl-version }}
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ matrix.perl-version }}
    - name: Install dependencies
      run: |
        mkdir -p ~/perl5 ~/python ~/usr
        export PERL=~/perl5
        export PYTHONPATH=~/python
        sudo apt-get update && sudo apt-get install -y scons libdbi-perl
        pip install coverage
        cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Codecov Test::Exception Test::Output Test::MockModule Devel::Cover MIME::Lite
        git clone --depth=5 https://github.com/salilab/saliweb
        (cd saliweb && scons modeller_key=UNKNOWN pythondir=$PYTHONPATH perldir=$PERB prefix=~/usr webdir=~/www install && touch $PYTHONPATH/saliweb/frontend/config.py)
    - name: Test
      run: |
        export PERL5LIB=~/perl5:$PERL5LIB
        export PYTHONPATH=~/python
        scons coverage=true python=$(which python) test
    - name: Upload coverage to codecov
      run: |
        bash <(curl -s https://codecov.io/bash)
        cover -report codecov
